name: CI

on:
  pull_request:
  push:
    branches: [main]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test server
        # Runs tests on server-side code
        run: |
          cd mern/server
          npm install
          npm run test

        # Runs tests on client-side code
      - uses: actions/checkout@v3
      - name: Test client
        run: |
          cd mern/client
          npm install
          npm run test

      - name: Deploy server
        # Only run this step if the branch is main
        if: github.ref == 'refs/heads/main'
        env:
          deploy_server_url: ${{ secrets.RENDER_DEPLOY_HOOK_SERVER }}
        run: |
          cd mern/server
          curl "$deploy_server_url"

      - name: Deploy client
        # Only run this step if the branch is main
        if: github.ref == 'refs/heads/main'
        env:
          deploy_client_url: ${{ secrets.RENDER_DEPLOY_HOOK_CLIENT }}
        run: |
          cd mern/client
          curl "$deploy_client_url"